### ISSUE TITLE
J4TS 0.2.0 Jar Files Missing the complete list of java.awt

### ISSUE THREAD

**Issue by nathanawmk** [j4ts/j4ts-awt-swing#1]
Hi j4ts experts, please help... J4TS 0.2.0 Jar Files Missing the complete list of java.awt. For example, it does not have import java.awt.Checkbox; import java.awt.Choice; import java.awt.Font;.

Is there a J4TS Jar file that contains support for the full list of AWT?

import java.applet.Applet;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.Choice;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.TextArea;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

![j4ts](https://user-images.githubusercontent.com/14244560/36372684-b52ae0ea-15a0-11e8-9b2f-ecdf25167587.png)

**Comment by schaumb** [comment]
I answered this question here: https://github.com/j4ts/j4ts/issues/27

It need a release sometime (probably).
